---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  volumes:
    - name: conjur-access-token
      emptyDir:
        medium: Memory

  containers:
  - name: webapp-authenticator
    image: webapp:local
    command: [ sleep, infinity ]
    env:
    - name: CONJUR_APPLIANCE_URL
      value: https://conjur-follower.conjur.svc.cluster.local/api
    - name: CONJUR_AUTHN_URL
      value: https://conjur-follower.conjur.svc.cluster.local/api/authn-k8s/minikube/default
    - name: CONJUR_ACCOUNT
      value: dev
    - name: CONJUR_AUTHN_LOGIN
      value: webapp
    - name: CONJUR_MAJOR_VERSION
      value: "4"
    - name: CONJUR_SSL_CERTIFICATE
      valueFrom:
        configMapKeyRef:
          name: webapp
          key: ssl_certificate
    - name: CONJUR_CLIENT_API_KEY
      valueFrom:
        secretKeyRef:
          name: conjur-client-api-key
          key: api-key
    volumeMounts:
    - mountPath: /run/conjur
      name: conjur-access-token
