---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  labels:
    app: haproxy-conjur-master
spec:
  ports:
  - port: 443
    name: https
  - port: 5432
    name: pg-main
  selector:
    app: haproxy-conjur-master
  externalIPs:
    - 192.168.99.100		# you can get this value w/ "minikube ip" command
---
apiVersion: v1
kind: Pod
metadata:
  name: haproxy-conjur-master
  labels:
    app: haproxy-conjur-master
spec:
  containers:
  - name: haproxy
    image: haproxy:conjur
    ports:
    - containerPort: 443
      name: https
    - containerPort: 636
      name: ldaps
    - containerPort: 5432
      name: pg-main
    - containerPort: 5433
      name: pg-audit
