FROM haproxy:1.7

RUN apt-get update 
RUN apt-get install -y bash 
RUN apt-get install -y curl 
RUN apt-get install -y jq 
RUN apt-get install -y vim

COPY conjur-health-check.sh /root/conjur-health-check.sh
			# config file is created in initcontainer
#COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

# For debugging: on container startup, wait forever for interrupt signal
#CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
