#!/bin/bash -e
#
# Usage: ./http_servers.sh
#
# Generates a list of conjur-master HTTP servers in HAProxy format into http_servers.cfg.
# Pod names & IP addresses are obtained via kubectl.

destination_file="http_servers.cfg"

cat <<CONFIG > $destination_file
# This file is generated by http_servers.sh

backend b_conjur_master_http
	mode tcp
	balance static-rr
	option external-check
	default-server inter 5s fall 3 rise 2
	external-check path "/usr/bin:/usr/local/bin"
	external-check command "/root/conjur-health-check.sh"
CONFIG

pod_list=$(kubectl get pods -lapp=conjur-appliance | awk '/conjur-master/ {print $1}')
for pod_name in $pod_list; do
	pod_ip=$(kubectl describe pod $pod_name | awk '/IP:/ {print $2}')
	echo -e '\t' server $pod_name $pod_ip:443 check >> $destination_file
done

exit 0
